oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

mysite_hello_world:
    resource: "@MYSITEHelloWorldBundle/Resources/config/routing.yml"
    prefix:   /


